export const kabasta = [
    {
      "id": 1,
      "nazhraniva": "Grahorica",
      "sm": 213.4,
      "sp": 197.3,
      "ssp": 121.8,
      "ee": 2.95,
      "sc": 260.1,
      "kolicina": 0, "izmenaKol": "promenaKolKabasto",  "pep": 1.61,
      "ca": 13.6,
      "p": 3.30,
      "nelmj": 6.33,
      "nemmj": 6.51,
      "Kategorija": "ZELENA I SOČNA HRANIVA"
    },
    {
      "id": 2,
      "nazhraniva": "Grahorica i ovas smesa",
      "sm": 194.7,
      "sp": 166.90,
      "ssp": 118.10,
      "ee": 0.57,
      "sc": 284.0,
      "kolicina": 0, "izmenaKol": "promenaKolKabasto",  "pep": 1.89,
      "ca": 9.8,
      "p": 3.60,
      "nelmj": 5.55,
      "nemmj": 5.50,
      "Kategorija": "ZELENA I SOČNA HRANIVA"
    },
    {
      "id": 3,
      "nazhraniva": "Grašak stočni",
      "sm": 202.0,
      "sp": 183.7,
      "ssp": 128.7,
      "ee": 0.58,
      "sc": 237.10,
      "kolicina": 0, "izmenaKol": "promenaKolKabasto",  "pep": 2.19,
      "ca": 10.4,
      "p": 2.0,
      "nelmj": 5.94,
      "nemmj": 6.04,
      "Kategorija": "ZELENA I SOČNA HRANIVA"
    },
    {
      "id": 4,
      "nazhraniva": "Kelj stočni",
      "sm": 126.0,
      "sp": 215.10,
      "ssp": 166.7,
      "ee": 0.42,
      "sc": 192.9,
      "kolicina": 0, "izmenaKol": "promenaKolKabasto",  "pep": 2.13,
      "ca": 11.9,
      "p": 4.0,
      "nelmj": 5.95,
      "nemmj": 6.11,
      "Kategorija": "ZELENA I SOČNA HRANIVA"
    },
    {
      "id": 5,
      "nazhraniva": "Krompir, krtole",
      "sm": 206.8,
      "sp": 86.6,
      "ssp": 43.0,
      "ee": 0.15,
      "sc": 38.2,
      "kolicina": 0, "izmenaKol": "promenaKolKabasto",  "pep": 1.04,
      "ca": 0.5,
      "p": 2.4,
      "nelmj": 7.21,
      "nemmj": 7.83,
      "Kategorija": "ZELENA I SOČNA HRANIVA"
    },
    {
      "id": 6,
      "nazhraniva": "Kukuruz, zeleni",
      "sm": 258.6,
      "sp": 79.7,
      "ssp": 50.3,
      "ee": 0.6,
      "sc": 218.9,
      "kolicina": 0, "izmenaKol": "promenaKolKabasto",  "pep": 1.51,
      "ca": 2.7,
      "p": 1.9,
      "nelmj": 6.11,
      "nemmj": 6.26,
      "Kategorija": "ZELENA I SOČNA HRANIVA"
    },
    {
      "id": 7,
      "nazhraniva": "Kupus",
      "sm": 100.9,
      "sp": 199.2,
      "ssp": 148.7,
      "ee": 0.22,
      "sc": 149.7,
      "kolicina": 0, "izmenaKol": "promenaKolKabasto",  "pep": 1.37,
      "ca": 5.9,
      "p": 3,
      "nelmj": 6.64,
      "nemmj": 7.04,
      "Kategorija": "ZELENA I SOČNA HRANIVA"
    },
    {
      "id": 8,
      "nazhraniva": "Lucerka",
      "sm": 227.6,
      "sp": 211.3,
      "ssp": 171.4,
      "ee": 0.52,
      "sc": 251.3,
      "kolicina": 0, "izmenaKol": "promenaKolKabasto",  "pep": 2.23,
      "ca": 21.1,
      "p": 3.5,
      "nelmj": 5.98,
      "nemmj": 6.06,
      "Kategorija": "ZELENA I SOČNA HRANIVA"
    },
    {
      "id": 9,
      "nazhraniva": "Lucerka, provenula",
      "sm": 473.9,
      "sp": 197.7,
      "ssp": 154.0,
      "ee": 1.28,
      "sc": 251.1,
      "kolicina": 0, "izmenaKol": "promenaKolKabasto",  "pep": 4.05,
      "ca": 12.2,
      "p": 2.5,
      "nelmj": 6.01,
      "nemmj": 6.1,
      "Kategorija": "ZELENA I SOČNA HRANIVA"
    },
    {
      "id": 10,
      "nazhraniva": "Mrkva,koren",
      "sm": 119,
      "sp": 109.2,
      "ssp": 75.6,
      "ee": 0.3,
      "sc": 109.2,
      "kolicina": 0, "izmenaKol": "promenaKolKabasto",  "pep": 1.3,
      "ca": 4.2,
      "p": 3.4,
      "nelmj": 6.97,
      "nemmj": 7.56,
      "Kategorija": "ZELENA I SOČNA HRANIVA"
    },
    {
      "id": 11,
      "nazhraniva": "Mrkva stočna, koren",
      "sm": 135,
      "sp": 103.7,
      "ssp": 74.1,
      "ee": 0.3,
      "sc": 88.9,
      "kolicina": 0, "izmenaKol": "promenaKolKabasto",  "pep": 2.5,
      "ca": 3.7,
      "p": 3,
      "nelmj": 6.67,
      "nemmj": 7.26,
      "Kategorija": "ZELENA I SOČNA HRANIVA"
    },
    {
      "id": 12,
      "nazhraniva": "Raž",
      "sm": 190.1,
      "sp": 145.2,
      "ssp": 110.5,
      "ee": 0.65,
      "sc": 299.3,
      "kolicina": 0, "izmenaKol": "promenaKolKabasto",  "pep": 1.69,
      "ca": 4.2,
      "p": 3.2,
      "nelmj": 6.15,
      "nemmj": 6.37,
      "Kategorija": "ZELENA I SOČNA HRANIVA"
    },
    {
      "id": 13,
      "nazhraniva": "Raž i grašak(smeša)",
      "sm": 163.2,
      "sp": 161.2,
      "ssp": 122.5,
      "ee": 0.48,
      "sc": 262.3,
      "kolicina": 0, "izmenaKol": "promenaKolKabasto",  "pep": 1.2,
      "ca": 19,
      "p": 8.6,
      "nelmj": 6.25,
      "nemmj": 6.37,
      "Kategorija": "ZELENA I SOČNA HRANIVA"
    },
    {
      "id": 14,
      "nazhraniva": "Raž i uljana repica (smeša)",
      "sm": 128.2,
      "sp": 234,
      "ssp": 148.2,
      "ee": 0.48,
      "sc": 268.3,
      "kolicina": 0, "izmenaKol": "promenaKolKabasto",  "pep": 1.54,
      "ca": 10.1,
      "p": 2.3,
      "nelmj": 6.24,
      "nemmj": 6.4,
      "Kategorija": "ZELENA I SOČNA HRANIVA"
    },
    {
      "id": 15,
      "nazhraniva": "Repa šećerna",
      "sm": 171.9,
      "sp": 112.3,
      "ssp": 81.4,
      "ee": 0.25,
      "sc": 101.2,
      "kolicina": 0, "izmenaKol": "promenaKolKabasto",  "pep": 1.98,
      "ca": 11.6,
      "p": 2.3,
      "nelmj": 5.64,
      "nemmj": 5.82,
      "Kategorija": "ZELENA I SOČNA HRANIVA"
    },
    {
      "id": 16,
      "nazhraniva": "Repa šećerna, koren",
      "sm": 205.8,
      "sp": 74.3,
      "ssp": 43.7,
      "ee": 0.29,
      "sc": 78.2,
      "kolicina": 0, "izmenaKol": "promenaKolKabasto",  "pep": 1.6,
      "ca": 15.5,
      "p": 2.9,
      "nelmj": 7.19,
      "nemmj": 7.87,
      "Kategorija": "ZELENA I SOČNA HRANIVA"
    },
    {
      "id": 17,
      "nazhraniva": "Repa šećerna, lišce",
      "sm": 136.8,
      "sp": 166.7,
      "ssp": 131.6,
      "ee": 0.32,
      "sc": 130.1,
      "kolicina": 0, "izmenaKol": "promenaKolKabasto",  "pep": 3.2,
      "ca": 10.2,
      "p": 2.2,
      "nelmj": 4.9,
      "nemmj": 4.97,
      "Kategorija": "ZELENA I SOČNA HRANIVA"
    },
    {
      "id": 18,
      "nazhraniva": "Repa šećerna, lišce i glave",
      "sm": 177.2,
      "sp": 151.8,
      "ssp": 124.2,
      "ee": 0.22,
      "sc": 137.7,
      "kolicina": 0, "izmenaKol": "promenaKolKabasto",  "pep": 2.98,
      "ca": 10.2,
      "p": 2.3,
      "nelmj": 6.38,
      "nemmj": 6.83,
      "Kategorija": "ZELENA I SOČNA HRANIVA"
    },
    {
      "id": 19,
      "nazhraniva": "Repa stočna",
      "sm": 143.4,
      "sp": 136.7,
      "ssp": 132.5,
      "ee": 0.11,
      "sc": 115.8,
      "kolicina": 0, "izmenaKol": "promenaKolKabasto",  "pep": 1.8,
      "ca": 1.4,
      "p": 3.5,
      "nelmj": 5.72,
      "nemmj": 5.86,
      "Kategorija": "ZELENA I SOČNA HRANIVA"
    },
    {
      "id": 20,
      "nazhraniva": "Sirak,krmni",
      "sm": 185.2,
      "sp": 111.8,
      "ssp": 75.6,
      "ee": 0.41,
      "sc": 287.8,
      "kolicina": 0, "izmenaKol": "promenaKolKabasto",  "pep": 1.41,
      "ca": 3.8,
      "p": 2.2,
      "nelmj": 5.45,
      "nemmj": 5.45,
      "Kategorija": "ZELENA I SOČNA HRANIVA"
    },
    {
      "id": 21,
      "nazhraniva": "Sirak,krmni",
      "sm": 290.5,
      "sp": 88.5,
      "ssp": 41.3,
      "ee": 0.74,
      "sc": 257.1,
      "kolicina": 0, "izmenaKol": "promenaKolKabasto",  "pep": 1.99,
      "ca": 3.8,
      "p": 2.1,
      "nelmj": 5.61,
      "nemmj": 5.68,
      "Kategorija": "ZELENA I SOČNA HRANIVA"
    },
    {
      "id": 22,
      "nazhraniva": "Soja",
      "sm": 250.5,
      "sp": 185.2,
      "ssp": 147.7,
      "ee": 0.74,
      "sc": 259.5,
      "kolicina": 0, "izmenaKol": "promenaKolKabasto",  "pep": 2.56,
      "ca": 15.2,
      "p": 3.2,
      "nelmj": 5.51,
      "nemmj": 5.47,
      "Kategorija": "ZELENA I SOČNA HRANIVA"
    },
    {
      "id": 23,
      "nazhraniva": "Sudanska trava",
      "sm": 234.7,
      "sp": 90.3,
      "ssp": 59.7,
      "ee": 0.65,
      "sc": 344.3,
      "kolicina": 0, "izmenaKol": "promenaKolKabasto",  "pep": 1.6,
      "ca": 5.1,
      "p": 3.8,
      "nelmj": 5.97,
      "nemmj": 6.05,
      "Kategorija": "ZELENA I SOČNA HRANIVA"
    },
    {
      "id": 24,
      "nazhraniva": "Suncokret",
      "sm": 150.9,
      "sp": 153.7,
      "ssp": 91.5,
      "ee": 0.48,
      "sc": 235.9,
      "kolicina": 0, "izmenaKol": "promenaKolKabasto",  "pep": 1.98,
      "ca": 15.9,
      "p": 3.3,
      "nelmj": 5.57,
      "nemmj": 5.63,
      "Kategorija": "ZELENA I SOČNA HRANIVA"
    },
    {
      "id": 25,
      "nazhraniva": "Trava livadska",
      "sm": 289.7,
      "sp": 141.5,
      "ssp": 100.1,
      "ee": 0.97,
      "sc": 250.3,
      "kolicina": 0, "izmenaKol": "promenaKolKabasto",  "pep": 2.72,
      "ca": 4.5,
      "p": 2.4,
      "nelmj": 5.21,
      "nemmj": 5.11,
      "Kategorija": "ZELENA I SOČNA HRANIVA"
    },
    {
      "id": 26,
      "nazhraniva": "Uljana repica",
      "sm": 136.3,
      "sp": 174.6,
      "ssp": 139.4,
      "ee": 0.43,
      "sc": 237.7,
      "kolicina": 0, "izmenaKol": "promenaKolKabasto",  "pep": 1.76,
      "ca": 13.2,
      "p": 3.7,
      "nelmj": 6.6,
      "nemmj": 7.04,
      "Kategorija": "ZELENA I SOČNA HRANIVA"
    },
    {
      "id": 38,
      "nazhraniva": "Graskova vreza",
      "sm": 224.6,
      "sp": 151.8,
      "ssp": 106.9,
      "ee": 0.91,
      "sc": 278.3,
      "kolicina": 0, "izmenaKol": "promenaKolKabasto",  "pep": 3.38,
      "ca": 14.2,
      "p": 2.7,
      "nelmj": 5.79,
      "nemmj": 5.92,
      "Kategorija": "SILAZA"
    },
    {
      "id": 39,
      "nazhraniva": "Kukuruz 13%",
      "sm": 129.4,
      "sp": 108.2,
      "ssp": 61.8,
      "ee": 0.45,
      "sc": 313,
      "kolicina": 0, "izmenaKol": "promenaKolKabasto",  "pep": 1.05,
      "ca": 7,
      "p": 5.4,
      "nelmj": 5.1,
      "nemmj": 4.95,
      "Kategorija": "SILAZA"
    },
    {
      "id": 40,
      "nazhraniva": "Kukuruz 16.8%",
      "sm": 168.2,
      "sp": 104,
      "ssp": 59.5,
      "ee": 0.59,
      "sc": 305.6,
      "kolicina": 0, "izmenaKol": "promenaKolKabasto",  "pep": 1.54,
      "ca": 5.4,
      "p": 4.2,
      "nelmj": 5.05,
      "nemmj": 4.93,
      "Kategorija": "SILAZA"
    },
    {
      "id": 41,
      "nazhraniva": "Kukuruz 21.4%",
      "sm": 214.1,
      "sp": 92.9,
      "ssp": 51.4,
      "ee": 0.65,
      "sc": 257.8,
      "kolicina": 0, "izmenaKol": "promenaKolKabasto",  "pep": 1.74,
      "ca": 4.2,
      "p": 3.3,
      "nelmj": 5.14,
      "nemmj": 5,
      "Kategorija": "SILAZA"
    },
    {
      "id": 42,
      "nazhraniva": "Kukuruz 25.9%",
      "sm": 258.6,
      "sp": 83.1,
      "ssp": 46.4,
      "ee": 0.77,
      "sc": 235.1,
      "kolicina": 0, "izmenaKol": "promenaKolKabasto",  "pep": 1.84,
      "ca": 3.5,
      "p": 2.7,
      "nelmj": 5.18,
      "nemmj": 5.1,
      "Kategorija": "SILAZA"
    },
    {
      "id": 43,
      "nazhraniva": "Kukuruz 34.48%",
      "sm": 344.8,
      "sp": 69,
      "ssp": 37.7,
      "ee": 1.03,
      "sc": 188.5,
      "kolicina": 0, "izmenaKol": "promenaKolKabasto",  "pep": 2.03,
      "ca": 2.6,
      "p": 2,
      "nelmj": 6,
      "nemmj": 6.18,
      "Kategorija": "SILAZA"
    },
    {
      "id": 44,
      "nazhraniva": "Kukuruz 38.33%",
      "sm": 383.3,
      "sp": 77.5,
      "ssp": 41.7,
      "ee": 1.06,
      "sc": 201.1,
      "kolicina": 0, "izmenaKol": "promenaKolKabasto",  "pep": 2.39,
      "ca": 3.9,
      "p": 2.1,
      "nelmj": 5.22,
      "nemmj": 5.14,
      "Kategorija": "SILAZA"
    },
    {
      "id": 45,
      "nazhraniva": "Zrno kukuruza,prekrupa",
      "sm": 665.9,
      "sp": 93.7,
      "ssp": 67.6,
      "ee": 2.82,
      "sc": 37.1,
      "kolicina": 0, "izmenaKol": "promenaKolKabasto",  "pep": 1.07,
      "ca": 3.2,
      "p": 0.2,
      "nelmj": 8.71,
      "nemmj": 9.73,
      "Kategorija": "SILAZA"
    },
    {
      "id": 46,
      "nazhraniva": "Kukuruzni klip,prekrupa",
      "sm": 623.8,
      "sp": 84,
      "ssp": 44.9,
      "ee": 2.43,
      "sc": 78.9,
      "kolicina": 0, "izmenaKol": "promenaKolKabasto",  "pep": 1.02,
      "ca": 1.1,
      "p": 2.4,
      "nelmj": 7.9,
      "nemmj": 8.64,
      "Kategorija": "SILAZA"
    },
    {
      "id": 47,
      "nazhraniva": "Kukuruz+lisceglave sec.repa",
      "sm": 233.4,
      "sp": 105.8,
      "ssp": 60,
      "ee": 0.54,
      "sc": 216.8,
      "kolicina": 0, "izmenaKol": "promenaKolKabasto",  "pep": 3.27,
      "ca": 0,
      "p": 0,
      "nelmj": 5.44,
      "nemmj": 5.48,
      "Kategorija": "SILAZA"
    },
    {
      "id": 48,
      "nazhraniva": "Kukuruzovina+lis.i.gl.sr",
      "sm": 250.5,
      "sp": 93,
      "ssp": 47.9,
      "ee": 0.53,
      "sc": 283.4,
      "kolicina": 0, "izmenaKol": "promenaKolKabasto",  "pep": 3.47,
      "ca": 0,
      "p": 0,
      "nelmj": 4.99,
      "nemmj": 4.91,
      "Kategorija": "SILAZA"
    },
    {
      "id": 49,
      "nazhraniva": "Lucerka",
      "sm": 282.6,
      "sp": 173,
      "ssp": 116.8,
      "ee": 1.04,
      "sc": 259.4,
      "kolicina": 0, "izmenaKol": "promenaKolKabasto",  "pep": 3.34,
      "ca": 18,
      "p": 2.8,
      "nelmj": 4.95,
      "nemmj": 4.81,
      "Kategorija": "SILAZA"
    },
    {
      "id": 50,
      "nazhraniva": "Lucerka senaza",
      "sm": 537.3,
      "sp": 192.3,
      "ssp": 130.8,
      "ee": 1.09,
      "sc": 287.9,
      "kolicina": 0, "izmenaKol": "promenaKolKabasto",  "pep": 5.03,
      "ca": 17.9,
      "p": 2.8,
      "nelmj": 4.99,
      "nemmj": 4.82,
      "Kategorija": "SILAZA"
    },
    {
      "id": 51,
      "nazhraniva": "Ovas",
      "sm": 220.8,
      "sp": 115,
      "ssp": 67.9,
      "ee": 0.97,
      "sc": 265.9,
      "kolicina": 0, "izmenaKol": "promenaKolKabasto",  "pep": 2.98,
      "ca": 4.5,
      "p": 3.2,
      "nelmj": 4.53,
      "nemmj": 4.3,
      "Kategorija": "SILAZA"
    },
    {
      "id": 52,
      "nazhraniva": "Pivski trop",
      "sm": 224,
      "sp": 278.1,
      "ssp": 200.9,
      "ee": 1.71,
      "sc": 177.7,
      "kolicina": 0, "izmenaKol": "promenaKolKabasto",  "pep": 0.96,
      "ca": 3.1,
      "p": 4.9,
      "nelmj": 6.25,
      "nemmj": 6.25,
      "Kategorija": "SILAZA"
    },
    {
      "id": 53,
      "nazhraniva": "Raz",
      "sm": 223.4,
      "sp": 107.4,
      "ssp": 71.6,
      "ee": 0.87,
      "sc": 354.5,
      "kolicina": 0, "izmenaKol": "promenaKolKabasto",  "pep": 2.47,
      "ca": 4,
      "p": 3.1,
      "nelmj": 5.42,
      "nemmj": 5.37,
      "Kategorija": "SILAZA"
    },
    {
      "id": 54,
      "nazhraniva": "Rezanci secerne repe",
      "sm": 141.2,
      "sp": 112.6,
      "ssp": 70.8,
      "ee": 0.22,
      "sc": 259.9,
      "kolicina": 0, "izmenaKol": "promenaKolKabasto",  "pep": 0.95,
      "ca": 7.1,
      "p": 0.7,
      "nelmj": 6.52,
      "nemmj": 6.87,
      "Kategorija": "SILAZA"
    },
    {
      "id": 55,
      "nazhraniva": "Sirak ",
      "sm": 246.8,
      "sp": 79.8,
      "ssp": 44.6,
      "ee": 0.75,
      "sc": 299,
      "kolicina": 0, "izmenaKol": "promenaKolKabasto",  "pep": 1.44,
      "ca": 2.8,
      "p": 1.6,
      "nelmj": 4.66,
      "nemmj": 4.42,
      "Kategorija": "SILAZA"
    },
    {
      "id": 56,
      "nazhraniva": "Sudanska trava",
      "sm": 169.7,
      "sp": 124.9,
      "ssp": 82.5,
      "ee": 0.44,
      "sc": 369.5,
      "kolicina": 0, "izmenaKol": "promenaKolKabasto",  "pep": 1.35,
      "ca": 4.7,
      "p": 1.8,
      "nelmj": 5.48,
      "nemmj": 5.42,
      "Kategorija": "SILAZA"
    },
    {
      "id": 57,
      "nazhraniva": "Suncokret",
      "sm": 158.5,
      "sp": 119.9,
      "ssp": 71.9,
      "ee": 0.58,
      "sc": 263.1,
      "kolicina": 0, "izmenaKol": "promenaKolKabasto",  "pep": 1.79,
      "ca": 14.5,
      "p": 3.2,
      "nelmj": 4.42,
      "nemmj": 4.1,
      "Kategorija": "SILAZA"
    },
    {
      "id": 58,
      "nazhraniva": "Trava livadska",
      "sm": 300.6,
      "sp": 108.4,
      "ssp": 66.5,
      "ee": 1.1,
      "sc": 291.7,
      "kolicina": 0, "izmenaKol": "promenaKolKabasto",  "pep": 2.34,
      "ca": 2.3,
      "p": 3.7,
      "nelmj": 5.12,
      "nemmj": 4.99,
      "Kategorija": "SILAZA"
    },
    {
      "id": 59,
      "nazhraniva": "Uljana repica",
      "sm": 147.4,
      "sp": 160.1,
      "ssp": 108.5,
      "ee": 0.79,
      "sc": 236.1,
      "kolicina": 0, "izmenaKol": "promenaKolKabasto",  "pep": 2.39,
      "ca": 12.2,
      "p": 3.4,
      "nelmj": 6.51,
      "nemmj": 6.85,
      "Kategorija": "SILAZA"
    },
    {
      "id": 88,
      "nazhraniva": "Graskova vreza dehidr.",
      "sm": 895.5,
      "sp": 159.2,
      "ssp": 141.6,
      "ee": 2.9,
      "sc": 258,
      "kolicina": 0, "izmenaKol": "promenaKolKabasto",  "pep": 10.67,
      "ca": 14.2,
      "p": 2.7,
      "nelmj": 3.89,
      "nemmj": 3.5,
      "Kategorija": "SUVA I DEHIDRIRANA HRANIVA"
    },
    {
      "id": 89,
      "nazhraniva": "Kukuruzna biljka dehidr.",
      "sm": 894,
      "sp": 88,
      "ssp": 48.1,
      "ee": 2.36,
      "sc": 221.4,
      "kolicina": 0, "izmenaKol": "promenaKolKabasto",  "pep": 5.64,
      "ca": 4.4,
      "p": 2.2,
      "nelmj": 5.59,
      "nemmj": 5.63,
      "Kategorija": "SUVA I DEHIDRIRANA HRANIVA"
    },
    {
      "id": 90,
      "nazhraniva": "Kukuruzovina",
      "sm": 580.4,
      "sp": 43.6,
      "ssp": 15.5,
      "ee": 0.57,
      "sc": 205.5,
      "kolicina": 0, "izmenaKol": "promenaKolKabasto",  "pep": 3.79,
      "ca": 5.5,
      "p": 0.9,
      "nelmj": 4.67,
      "nemmj": 4.5,
      "Kategorija": "SUVA I DEHIDRIRANA HRANIVA"
    },
    {
      "id": 91,
      "nazhraniva": "Kukuruzovina",
      "sm": 799.2,
      "sp": 47.8,
      "ssp": 16.3,
      "ee": 1.44,
      "sc": 337.8,
      "kolicina": 0, "izmenaKol": "promenaKolKabasto",  "pep": 5.15,
      "ca": 7.9,
      "p": 2.9,
      "nelmj": 4.45,
      "nemmj": 4.15,
      "Kategorija": "SUVA I DEHIDRIRANA HRANIVA"
    },
    {
      "id": 92,
      "nazhraniva": "Lucerkino brasno",
      "sm": 911.3,
      "sp": 199.9,
      "ssp": 149.2,
      "ee": 2.61,
      "sc": 243.7,
      "kolicina": 0, "izmenaKol": "promenaKolKabasto",  "pep": 8.99,
      "ca": 16.5,
      "p": 3,
      "nelmj": 5.53,
      "nemmj": 5.52,
      "Kategorija": "SUVA I DEHIDRIRANA HRANIVA"
    },
    {
      "id": 93,
      "nazhraniva": "Seno lucerke",
      "sm": 856.5,
      "sp": 181.2,
      "ssp": 129.6,
      "ee": 1.75,
      "sc": 282.9,
      "kolicina": 0, "izmenaKol": "promenaKolKabasto",  "pep": 7.59,
      "ca": 24.8,
      "p": 3,
      "nelmj": 4.95,
      "nemmj": 4.76,
      "Kategorija": "SUVA I DEHIDRIRANA HRANIVA"
    },
    {
      "id": 94,
      "nazhraniva": "Seno muhara",
      "sm": 837.3,
      "sp": 85.8,
      "ssp": 102.6,
      "ee": 2.1,
      "sc": 325.6,
      "kolicina": 0, "izmenaKol": "promenaKolKabasto",  "pep": 8.05,
      "ca": 3.3,
      "p": 1.9,
      "nelmj": 4.57,
      "nemmj": 4.34,
      "Kategorija": "SUVA I DEHIDRIRANA HRANIVA"
    },
    {
      "id": 95,
      "nazhraniva": "Seno trava",
      "sm": 866.9,
      "sp": 109.5,
      "ssp": 65.8,
      "ee": 2.12,
      "sc": 303.1,
      "kolicina": 0, "izmenaKol": "promenaKolKabasto",  "pep": 6.63,
      "ca": 5.7,
      "p": 2.1,
      "nelmj": 4.48,
      "nemmj": 4.19,
      "Kategorija": "SUVA I DEHIDRIRANA HRANIVA"
    },
    {
      "id": 96,
      "nazhraniva": "Seno trava+lucerka",
      "sm": 862.3,
      "sp": 158.6,
      "ssp": 112.5,
      "ee": 2.15,
      "sc": 282,
      "kolicina": 0, "izmenaKol": "promenaKolKabasto",  "pep": 7.96,
      "ca": 11.7,
      "p": 2.6,
      "nelmj": 4.58,
      "nemmj": 4.33,
      "Kategorija": "SUVA I DEHIDRIRANA HRANIVA"
    },
    {
      "id": 97,
      "nazhraniva": "Seno crvene deteline",
      "sm": 841.7,
      "sp": 171.7,
      "ssp": 106.9,
      "ee": 2.61,
      "sc": 241.8,
      "kolicina": 0, "izmenaKol": "promenaKolKabasto",  "pep": 7.76,
      "ca": 15,
      "p": 2.5,
      "nelmj": 5.07,
      "nemmj": 4.92,
      "Kategorija": "SUVA I DEHIDRIRANA HRANIVA"
    },
    {
      "id": 98,
      "nazhraniva": "Slama ovsa",
      "sm": 865.1,
      "sp": 35.6,
      "ssp": 8.1,
      "ee": 1.45,
      "sc": 427,
      "kolicina": 0, "izmenaKol": "promenaKolKabasto",  "pep": 6,
      "ca": 2.5,
      "p": 7.1,
      "nelmj": 3.57,
      "nemmj": 3.1,
      "Kategorija": "SUVA I DEHIDRIRANA HRANIVA"
    },
    {
      "id": 99,
      "nazhraniva": "Slama psenice",
      "sm": 865.5,
      "sp": 38.2,
      "ssp": 8.1,
      "ee": 1.03,
      "sc": 385.1,
      "kolicina": 0, "izmenaKol": "promenaKolKabasto",  "pep": 7.51,
      "ca": 2.7,
      "p": 1.5,
      "nelmj": 2.26,
      "nemmj": 2.01,
      "Kategorija": "SUVA I DEHIDRIRANA HRANIVA"
    },
    {
      "id": 100,
      "nazhraniva": "Sojina biljka dehidr.",
      "sm": 886.6,
      "sp": 139.6,
      "ssp": 93.5,
      "ee": 2.37,
      "sc": 249.7,
      "kolicina": 0, "izmenaKol": "promenaKolKabasto",  "pep": 13.38,
      "ca": 14.5,
      "p": 3.9,
      "nelmj": 4.35,
      "nemmj": 4.13,
      "Kategorija": "SUVA I DEHIDRIRANA HRANIVA"
    }
  ];

  export const koncentrovana = [
    {
      "id": 27,
      "nazhraniva": "Grasak",
      "sm": 883.8,
      "sp": 255,
      "ssp": 183.3,
      "ee": 1.68,
      "sc": 84.9,
      "kolicina": 0, "izmenaKol": "promenaKolKoncentrovano",  "pep": 4.05,
      "ca": 2,
      "p": 6.2,
      "nelmj": 7.91,
      "nemmj": 8.61,
      "Kategorija": "ZRNEVLJE"
    },
    {
      "id": 28,
      "nazhraniva": "Jecam",
      "sm": 880.2,
      "sp": 124.3,
      "ssp": 89.8,
      "ee": 1.86,
      "sc": 55.6,
      "kolicina": 0, "izmenaKol": "promenaKolKoncentrovano",  "pep": 2.66,
      "ca": 0.5,
      "p": 3.7,
      "nelmj": 7.63,
      "nemmj": 8.32,
      "Kategorija": "ZRNEVLJE"
    },
    {
      "id": 29,
      "nazhraniva": "Kukuruz",
      "sm": 870.1,
      "sp": 100.4,
      "ssp": 72.4,
      "ee": 3.89,
      "sc": 35.6,
      "kolicina": 0, "izmenaKol": "promenaKolKoncentrovano",  "pep": 1.41,
      "ca": 0.3,
      "p": 3.1,
      "nelmj": 8.65,
      "nemmj": 9.65,
      "Kategorija": "ZRNEVLJE"
    },
    {
      "id": 30,
      "nazhraniva": "Kukuruz klipovi",
      "sm": 869.6,
      "sp": 95.9,
      "ssp": 50.6,
      "ee": 3.14,
      "sc": 197.2,
      "kolicina": 0, "izmenaKol": "promenaKolKoncentrovano",  "pep": 1.76,
      "ca": 0.8,
      "p": 2.6,
      "nelmj": 6.51,
      "nemmj": 6.73,
      "Kategorija": "ZRNEVLJE"
    },
    {
      "id": 31,
      "nazhraniva": "Ovas",
      "sm": 887.4,
      "sp": 136.9,
      "ssp": 103.7,
      "ee": 4.77,
      "sc": 98.4,
      "kolicina": 0, "izmenaKol": "promenaKolKoncentrovano",  "pep": 3.62,
      "ca": 0.7,
      "p": 3.8,
      "nelmj": 6.81,
      "nemmj": 7.14,
      "Kategorija": "ZRNEVLJE"
    },
    {
      "id": 32,
      "nazhraniva": "Proso",
      "sm": 888,
      "sp": 119.9,
      "ssp": 85.6,
      "ee": 4.61,
      "sc": 103,
      "kolicina": 0, "izmenaKol": "promenaKolKoncentrovano",  "pep": 4.52,
      "ca": 0.6,
      "p": 2.9,
      "nelmj": 6.98,
      "nemmj": 7.41,
      "Kategorija": "ZRNEVLJE"
    },
    {
      "id": 33,
      "nazhraniva": "Psenica",
      "sm": 889.1,
      "sp": 144.6,
      "ssp": 121.5,
      "ee": 1.53,
      "sc": 35.3,
      "kolicina": 0, "izmenaKol": "promenaKolKoncentrovano",  "pep": 1.92,
      "ca": 1.1,
      "p": 5.1,
      "nelmj": 8.11,
      "nemmj": 8.93,
      "Kategorija": "ZRNEVLJE"
    },
    {
      "id": 34,
      "nazhraniva": "Raz",
      "sm": 897.5,
      "sp": 147.7,
      "ssp": 130.4,
      "ee": 3.57,
      "sc": 87.4,
      "kolicina": 0, "izmenaKol": "promenaKolKoncentrovano",  "pep": 2.5,
      "ca": 0.7,
      "p": 3.7,
      "nelmj": 7.3,
      "nemmj": 7.8,
      "Kategorija": "ZRNEVLJE"
    },
    {
      "id": 35,
      "nazhraniva": "Sirak,krmni",
      "sm": 847.8,
      "sp": 110.4,
      "ssp": 81.4,
      "ee": 3.28,
      "sc": 43.2,
      "kolicina": 0, "izmenaKol": "promenaKolKoncentrovano",  "pep": 2.4,
      "ca": 0.4,
      "p": 3.9,
      "nelmj": 7.34,
      "nemmj": 7.89,
      "Kategorija": "ZRNEVLJE"
    },
    {
      "id": 36,
      "nazhraniva": "Soja",
      "sm": 894.6,
      "sp": 367.9,
      "ssp": 325.3,
      "ee": 17.68,
      "sc": 89.4,
      "kolicina": 0, "izmenaKol": "promenaKolKoncentrovano",  "pep": 5.67,
      "ca": 2.2,
      "p": 6.1,
      "nelmj": 10.32,
      "nemmj": 11.41,
      "Kategorija": "ZRNEVLJE"
    },
    {
      "id": 37,
      "nazhraniva": "Suncokret celo zrno",
      "sm": 959.2,
      "sp": 186,
      "ssp": 167.8,
      "ee": 43.7,
      "sc": 126.1,
      "kolicina": 0, "izmenaKol": "promenaKolKoncentrovano",  "pep": 2.89,
      "ca": 1.8,
      "p": 5.4,
      "nelmj": 13.77,
      "nemmj": 15.54,
      "Kategorija": "ZRNEVLJE"
    },
    {
      "id": 60,
      "nazhraniva": "Kikirikijeva sacma",
      "sm": 918.9,
      "sp": 498.1,
      "ssp": 468,
      "ee": 1.36,
      "sc": 103.1,
      "kolicina": 0, "izmenaKol": "promenaKolKoncentrovano",  "pep": 6.27,
      "ca": 2.9,
      "p": 6.7,
      "nelmj": 6.37,
      "nemmj": 6.43,
      "Kategorija": "SPOREDNI PROIZVODI PREHRAMBENE INDUSTRIJE"
    },
    {
      "id": 61,
      "nazhraniva": "Kukuruz bez klica",
      "sm": 880.2,
      "sp": 88.2,
      "ssp": 61.7,
      "ee": 1.08,
      "sc": 10.8,
      "kolicina": 0, "izmenaKol": "promenaKolKoncentrovano",  "pep": 0.49,
      "ca": 1.1,
      "p": 15.9,
      "nelmj": 8.6,
      "nemmj": 9.63,
      "Kategorija": "SPOREDNI PROIZVODI PREHRAMBENE INDUSTRIJE"
    },
    {
      "id": 62,
      "nazhraniva": "Kukuruzna dzibra",
      "sm": 80.8,
      "sp": 242.6,
      "ssp": 157.2,
      "ee": 0.83,
      "sc": 116.3,
      "kolicina": 0, "izmenaKol": "promenaKolKoncentrovano",  "pep": 0.43,
      "ca": 3.7,
      "p": 16.1,
      "nelmj": 7.3,
      "nemmj": 7.67,
      "Kategorija": "SPOREDNI PROIZVODI PREHRAMBENE INDUSTRIJE"
    },
    {
      "id": 63,
      "nazhraniva": "Kukuruzna drozdina,sveza",
      "sm": 386.4,
      "sp": 130.7,
      "ssp": 113.6,
      "ee": 0.92,
      "sc": 46.8,
      "kolicina": 0, "izmenaKol": "promenaKolKoncentrovano",  "pep": 0.3,
      "ca": 0.5,
      "p": 6,
      "nelmj": 8.36,
      "nemmj": 9.27,
      "Kategorija": "SPOREDNI PROIZVODI PREHRAMBENE INDUSTRIJE"
    },
    {
      "id": 64,
      "nazhraniva": "Kukuruzna drozdina,suva",
      "sm": 908.5,
      "sp": 216.2,
      "ssp": 185.9,
      "ee": 3.39,
      "sc": 140.6,
      "kolicina": 0, "izmenaKol": "promenaKolKoncentrovano",  "pep": 1.58,
      "ca": 0.6,
      "p": 5.9,
      "nelmj": 8.32,
      "nemmj": 9.07,
      "Kategorija": "SPOREDNI PROIZVODI PREHRAMBENE INDUSTRIJE"
    },
    {
      "id": 65,
      "nazhraniva": "Kukuruzne klice",
      "sm": 879.6,
      "sp": 141.4,
      "ssp": 120.2,
      "ee": 15.99,
      "sc": 42.4,
      "kolicina": 0, "izmenaKol": "promenaKolKoncentrovano",  "pep": 4.54,
      "ca": 1.1,
      "p": 4.3,
      "nelmj": 9.58,
      "nemmj": 10.63,
      "Kategorija": "SPOREDNI PROIZVODI PREHRAMBENE INDUSTRIJE"
    },
    {
      "id": 66,
      "nazhraniva": "Kukuruzno glutensko brasno",
      "sm": 915.4,
      "sp": 654.6,
      "ssp": 582.3,
      "ee": 5.62,
      "sc": 12,
      "kolicina": 0, "izmenaKol": "promenaKolKoncentrovano",  "pep": 1.65,
      "ca": 1.6,
      "p": 5.1,
      "nelmj": 9.72,
      "nemmj": 10.63,
      "Kategorija": "SPOREDNI PROIZVODI PREHRAMBENE INDUSTRIJE"
    },
    {
      "id": 67,
      "nazhraniva": "Kukurno glutensko hranivo",
      "sm": 899.4,
      "sp": 255.3,
      "ssp": 219,
      "ee": 3.48,
      "sc": 85.2,
      "kolicina": 0, "izmenaKol": "promenaKolKoncentrovano",  "pep": 1.12,
      "ca": 3.6,
      "p": 7.8,
      "nelmj": 8.68,
      "nemmj": 9.54,
      "Kategorija": "SPOREDNI PROIZVODI PREHRAMBENE INDUSTRIJE"
    },
    {
      "id": 68,
      "nazhraniva": "Lanena sacma",
      "sm": 931.2,
      "sp": 359.1,
      "ssp": 385.5,
      "ee": 1.48,
      "sc": 14.44,
      "kolicina": 0, "izmenaKol": "promenaKolKoncentrovano",  "pep": 8.6,
      "ca": 4.3,
      "p": 9.3,
      "nelmj": 6.37,
      "nemmj": 6.56,
      "Kategorija": "SPOREDNI PROIZVODI PREHRAMBENE INDUSTRIJE"
    },
    {
      "id": 69,
      "nazhraniva": "Melasa secerne repe",
      "sm": 728,
      "sp": 82.4,
      "ssp": 42.6,
      "ee": 0,
      "sc": 0,
      "kolicina": 0, "izmenaKol": "promenaKolKoncentrovano",  "pep": 7.2,
      "ca": 1.6,
      "p": 0.3,
      "nelmj": 7.16,
      "nemmj": 7.9,
      "Kategorija": "SPOREDNI PROIZVODI PREHRAMBENE INDUSTRIJE"
    },
    {
      "id": 70,
      "nazhraniva": "Pamukova sacma",
      "sm": 920.9,
      "sp": 442.8,
      "ssp": 332.3,
      "ee": 1.65,
      "sc": 120,
      "kolicina": 0, "izmenaKol": "promenaKolKoncentrovano",  "pep": 6.85,
      "ca": 2.2,
      "p": 11.2,
      "nelmj": 5.48,
      "nemmj": 5.33,
      "Kategorija": "SPOREDNI PROIZVODI PREHRAMBENE INDUSTRIJE"
    },
    {
      "id": 71,
      "nazhraniva": "Pivski trop svez",
      "sm": 211.6,
      "sp": 291.1,
      "ssp": 212.7,
      "ee": 1.71,
      "sc": 142.2,
      "kolicina": 0, "izmenaKol": "promenaKolKoncentrovano",  "pep": 0.78,
      "ca": 3.3,
      "p": 5.2,
      "nelmj": 6.47,
      "nemmj": 6.52,
      "Kategorija": "SPOREDNI PROIZVODI PREHRAMBENE INDUSTRIJE"
    },
    {
      "id": 72,
      "nazhraniva": "Pivski trop suv",
      "sm": 890,
      "sp": 301.2,
      "ssp": 211.2,
      "ee": 7.94,
      "sc": 166.4,
      "kolicina": 0, "izmenaKol": "promenaKolKoncentrovano",  "pep": 4.24,
      "ca": 3.4,
      "p": 6.4,
      "nelmj": 6.54,
      "nemmj": 6.6,
      "Kategorija": "SPOREDNI PROIZVODI PREHRAMBENE INDUSTRIJE"
    },
    {
      "id": 73,
      "nazhraniva": "Psenicne mekinje",
      "sm": 879.9,
      "sp": 176.8,
      "ssp": 135.2,
      "ee": 3.7,
      "sc": 105.6,
      "kolicina": 0, "izmenaKol": "promenaKolKoncentrovano",  "pep": 5.47,
      "ca": 1.3,
      "p": 14.3,
      "nelmj": 5.77,
      "nemmj": 5.82,
      "Kategorija": "SPOREDNI PROIZVODI PREHRAMBENE INDUSTRIJE"
    },
    {
      "id": 74,
      "nazhraniva": "Psenicno stocno brasno",
      "sm": 877.1,
      "sp": 167,
      "ssp": 142.5,
      "ee": 3.24,
      "sc": 55.2,
      "kolicina": 0, "izmenaKol": "promenaKolKoncentrovano",  "pep": 3.43,
      "ca": 1.3,
      "p": 14.4,
      "nelmj": 7.97,
      "nemmj": 8.72,
      "Kategorija": "SPOREDNI PROIZVODI PREHRAMBENE INDUSTRIJE"
    },
    {
      "id": 75,
      "nazhraniva": "Rezanci secerne repe svezi",
      "sm": 133.6,
      "sp": 108.5,
      "ssp": 74.9,
      "ee": 0.13,
      "sc": 241.8,
      "kolicina": 0, "izmenaKol": "promenaKolKoncentrovano",  "pep": 0.8,
      "ca": 7.5,
      "p": 0.7,
      "nelmj": 6.66,
      "nemmj": 7.04,
      "Kategorija": "SPOREDNI PROIZVODI PREHRAMBENE INDUSTRIJE"
    },
    {
      "id": 76,
      "nazhraniva": "rezanci sec.repe suvi",
      "sm": 888.9,
      "sp": 99.1,
      "ssp": 57.4,
      "ee": 0.86,
      "sc": 228.6,
      "kolicina": 0, "izmenaKol": "promenaKolKoncentrovano",  "pep": 3.94,
      "ca": 7.3,
      "p": 1,
      "nelmj": 7.08,
      "nemmj": 7.55,
      "Kategorija": "SPOREDNI PROIZVODI PREHRAMBENE INDUSTRIJE"
    },
    {
      "id": 77,
      "nazhraniva": "Repicina sacma",
      "sm": 897.8,
      "sp": 388.7,
      "ssp": 321.9,
      "ee": 1.71,
      "sc": 125.8,
      "kolicina": 0, "izmenaKol": "promenaKolKoncentrovano",  "pep": 6.86,
      "ca": 8.8,
      "p": 14.3,
      "nelmj": 6.5,
      "nemmj": 6.68,
      "Kategorija": "SPOREDNI PROIZVODI PREHRAMBENE INDUSTRIJE"
    },
    {
      "id": 78,
      "nazhraniva": "Repicine pogace",
      "sm": 922.5,
      "sp": 351.2,
      "ssp": 291.6,
      "ee": 10.5,
      "sc": 122.1,
      "kolicina": 0, "izmenaKol": "promenaKolKoncentrovano",  "pep": 6.22,
      "ca": 7.2,
      "p": 11.4,
      "nelmj": 7.83,
      "nemmj": 8.23,
      "Kategorija": "SPOREDNI PROIZVODI PREHRAMBENE INDUSTRIJE"
    },
    {
      "id": 79,
      "nazhraniva": "Sladne klice",
      "sm": 931.3,
      "sp": 280.3,
      "ssp": 224.4,
      "ee": 1.3,
      "sc": 131.4,
      "kolicina": 0, "izmenaKol": "promenaKolKoncentrovano",  "pep": 6.8,
      "ca": 2.4,
      "p": 7.8,
      "nelmj": 6.97,
      "nemmj": 7.38,
      "Kategorija": "SPOREDNI PROIZVODI PREHRAMBENE INDUSTRIJE"
    },
    {
      "id": 80,
      "nazhraniva": "Sladne klice",
      "sm": 951.6,
      "sp": 317,
      "ssp": 253.3,
      "ee": 2.58,
      "sc": 103.3,
      "kolicina": 0, "izmenaKol": "promenaKolKoncentrovano",  "pep": 5.79,
      "ca": 2.3,
      "p": 7.7,
      "nelmj": 6.54,
      "nemmj": 6.75,
      "Kategorija": "SPOREDNI PROIZVODI PREHRAMBENE INDUSTRIJE"
    },
    {
      "id": 81,
      "nazhraniva": "Stocni kvasac suv",
      "sm": 901,
      "sp": 510.7,
      "ssp": 459.5,
      "ee": 1.34,
      "sc": 2.11,
      "kolicina": 0, "izmenaKol": "promenaKolKoncentrovano",  "pep": 9.95,
      "ca": 1.6,
      "p": 15.8,
      "nelmj": 7.95,
      "nemmj": 8.61,
      "Kategorija": "SPOREDNI PROIZVODI PREHRAMBENE INDUSTRIJE"
    },
    {
      "id": 82,
      "nazhraniva": "Sojina sacma",
      "sm": 889,
      "sp": 500.1,
      "ssp": 474.7,
      "ee": 1.69,
      "sc": 75.7,
      "kolicina": 0, "izmenaKol": "promenaKolKoncentrovano",  "pep": 6.26,
      "ca": 3.8,
      "p": 7.1,
      "nelmj": 8.86,
      "nemmj": 9.46,
      "Kategorija": "SPOREDNI PROIZVODI PREHRAMBENE INDUSTRIJE"
    },
    {
      "id": 83,
      "nazhraniva": "Sojine pogace",
      "sm": 914.8,
      "sp": 430.4,
      "ssp": 366.2,
      "ee": 9.83,
      "sc": 66.4,
      "kolicina": 0, "izmenaKol": "promenaKolKoncentrovano",  "pep": 5.99,
      "ca": 3,
      "p": 7,
      "nelmj": 8.52,
      "nemmj": 9.15,
      "Kategorija": "SPOREDNI PROIZVODI PREHRAMBENE INDUSTRIJE"
    },
    {
      "id": 84,
      "nazhraniva": "Suncokret.sacma 33%",
      "sm": 900,
      "sp": 366.7,
      "ssp": 307.8,
      "ee": 1.5,
      "sc": 244.4,
      "kolicina": 0, "izmenaKol": "promenaKolKoncentrovano",  "pep": 5.5,
      "ca": 3.3,
      "p": 11.1,
      "nelmj": 6.12,
      "nemmj": 5.92,
      "Kategorija": "SPOREDNI PROIZVODI PREHRAMBENE INDUSTRIJE"
    },
    {
      "id": 85,
      "nazhraniva": "Suncokret.sacma 36%",
      "sm": 897.7,
      "sp": 405.9,
      "ssp": 340.9,
      "ee": 1.8,
      "sc": 200.5,
      "kolicina": 0, "izmenaKol": "promenaKolKoncentrovano",  "pep": 6.78,
      "ca": 3.3,
      "p": 11.6,
      "nelmj": 6.25,
      "nemmj": 6.1,
      "Kategorija": "SPOREDNI PROIZVODI PREHRAMBENE INDUSTRIJE"
    },
    {
      "id": 86,
      "nazhraniva": "Suncokret.sacma 42%",
      "sm": 900,
      "sp": 466.7,
      "ssp": 410.7,
      "ee": 1.5,
      "sc": 155.6,
      "kolicina": 0, "izmenaKol": "promenaKolKoncentrovano",  "pep": 7,
      "ca": 2.8,
      "p": 14.4,
      "nelmj": 7.38,
      "nemmj": 7.54,
      "Kategorija": "SPOREDNI PROIZVODI PREHRAMBENE INDUSTRIJE"
    },
    {
      "id": 87,
      "nazhraniva": "Suncokretove pogace",
      "sm": 942.3,
      "sp": 371.7,
      "ssp": 329,
      "ee": 8.97,
      "sc": 159.9,
      "kolicina": 0, "izmenaKol": "promenaKolKoncentrovano",  "pep": 7.04,
      "ca": 4,
      "p": 10.3,
      "nelmj": 6.14,
      "nemmj": 6.08,
      "Kategorija": "SPOREDNI PROIZVODI PREHRAMBENE INDUSTRIJE"
    },

    {
      "id": 101,
      "nazhraniva": "Kolagen",
      "sm": 871.6,
      "sp": 954.9,
      "ssp": 592.6,
      "ee": 0,
      "sc": 0,
      "kolicina": 0, "izmenaKol": "promenaKolKoncentrovano",  "pep": 1.09,
      "ca": 0.8,
      "p": 0,
      "nelmj": 5.93,
      "nemmj": 5.56,
      "Kategorija": "HRANIVA ZIVOTINJSKOG POREKLA"
    },
    {
      "id": 102,
      "nazhraniva": "Mesno brasno",
      "sm": 889.7,
      "sp": 545.9,
      "ssp": 423.7,
      "ee": 13.37,
      "sc": 2.83,
      "kolicina": 0, "izmenaKol": "promenaKolKoncentrovano",  "pep": 19.71,
      "ca": 63.1,
      "p": 32.5,
      "nelmj": 7.88,
      "nemmj": 8.41,
      "Kategorija": "HRANIVA ZIVOTINJSKOG POREKLA"
    },
    {
      "id": 103,
      "nazhraniva": "Obrano mleko u prahu",
      "sm": 945.6,
      "sp": 354.7,
      "ssp": 321.5,
      "ee": 0.43,
      "sc": 0,
      "kolicina": 0, "izmenaKol": "promenaKolKoncentrovano",  "pep": 7.93,
      "ca": 13.2,
      "p": 10.6,
      "nelmj": 8.54,
      "nemmj": 9.52,
      "Kategorija": "HRANIVA ZIVOTINJSKOG POREKLA"
    },
    {
      "id": 104,
      "nazhraniva": "Riblje b rasno",
      "sm": 915.6,
      "sp": 687.1,
      "ssp": 605.1,
      "ee": 7.51,
      "sc": 0.1,
      "kolicina": 0, "izmenaKol": "promenaKolKoncentrovano",  "pep": 16.52,
      "ca": 76.5,
      "p": 38.2,
      "nelmj": 7.4,
      "nemmj": 7.77,
      "Kategorija": "HRANIVA ZIVOTINJSKOG POREKLA"
    }
  ];

  export const mineralna = [
    
    {
      "id": 105,
      "nazhraniva": "DKF",
      "sm": 970,
      "sp": 0,
      "ssp": 0,
      "ee": 0,
      "sc": 0,
      "kolicina": 0, "izmenaKol": "promenaKolMineralno",  "pep": 0,
      "ca": 230,
      "p": 180,
      "nelmj": 0,
      "nemmj": 0,
      "Kategorija": "MINERALNA HRANIVA"
    },
    {
      "id": 106,
      "nazhraniva": "Stočna kreda",
      "sm": 990,
      "sp": 0,
      "ssp": 0,
      "ee": 0,
      "sc": 0,
      "kolicina": 0, "izmenaKol": "promenaKolMineralno",  "pep": 0,
      "ca": 380,
      "p": 0,
      "nelmj": 0,
      "nemmj": 0,
      "Kategorija": "MINERALNA HRANIVA"
    },
    {
      "id": 107,
      "nazhraniva": "Premiks",
      "sm": 990,
      "sp": 0,
      "ssp": 0,
      "ee": 0,
      "sc": 0,
      "kolicina": 0, "izmenaKol": "promenaKolMineralno",  "pep": 0,
      "ca": 220,
      "p": 40,
      "nelmj": 0,
      "nemmj": 0,
      "Kategorija": "MINERALNA HRANIVA"
    },
    {
      "id": 108,
      "nazhraniva": "MAP",
      "sm": 990,
      "sp": 700,
      "ssp": 0,
      "ee": 0,
      "sc": 0,
      "kolicina": 0, "izmenaKol": "promenaKolMineralno",  "pep": 0,
      "ca": 5,
      "p": 240,
      "nelmj": 0,
      "nemmj": 0,
      "Kategorija": "MINERALNA HRANIVA"
    }
    
  ]










